// test_200_3.B
begin
   println MdU - _b6; 
   if ((742622 * 037))
      while (_R)
         println 6; 
   else 
      _xNdw9U7 := 43 * 52049263; 
   newline; 
end
_U(_iImoA){local _7HCA, T, _5Llf, _Kuda; 
   newline; 
   return _pH; 
   {
   }
}
GOR2D8L(qtmH, mQ, j4){local _5f0XTo; 
   return (_d3) && !_Ct0v; 
   {
   }
}
_V(_SS_keRxCd1c){
   newline; 
}
TiupuN(Q5GAOooJ){local u, _v_MLTRhk, _l; 
   println 97; 
   {
   }
}
_8e9p_Ox(){local _R, _xk; 
}
_4RH(){
}