// test_200_47.B
begin
   if (N3Z && IAWZWP(_0$))
      {
         print 77122 - LYnI; 
         newline; 
      }
   else 
      newline; 
   zxljR(1, Y4i); 
   print _2u() < 6; 
   while (!z_xQlrmjIwV == YG())
      println _wu(68 <= 0255777, 510); 
   print 74; 
   {
   }
   newline; 
end
_NCW(B, p, TRV){local LPVQ2y8, i, D; 
   newline; 
   newline; 
   newline; 
}
_WQqEqv(_A, VRE4r, _M, _V){local t, _3, ua; 
}
_8(){
}