// test_400_28.B
begin
   return !!xfQiau() * (4); 
   print !Jyaqfe4 <= 14; 
   return !!293581 < _2; 
   {
      println _qC; 
      print _a0; 
      println 1127; 
   }
   mcZ93vw := (_8gq6BB) + _gtC$b8NM; 
   _bHFrZ(); 
   print 4 - F; 
   _a(lg3, I); 
   print _D4nY; 
end
_LE(r, _tbi1ZM){local _Jblfv, exJR, mWri; 
   return 8713; 
   newline; 
}
v(_f, _x, _y){local qs, l, _Sq9X, _l, O, rVqWMDv, GBzjO, _xlkjWk1; 
   while (13512464 <= 320)
      if (_lo(2, !E_) + (0665119))
         return (87 - 348) || (7 <= 1); 
      else 
         newline; 
   _o(); 
   {
   }
   newline; 
   newline; 
}
VJDTlmss(Bq){local iy9COy1; 
   printch 9 < 3; 
   printch Z; 
   newline; 
   println 67; 
   print _VBAIT; 
   {
   }
}
_VeK(Bo){local GD, aYV, S; 
   if (897)
      newline; 
   else 
      {
      }
   {
   }
}
_g(){
}
_b(){
   println _k; 
}
_hlNgYYnrW3(){
}