// test_200_10.B
begin
   _lU(); 
   return !536 < I; 
   while (8)
      newline; 
end
h(_4$k, HV35, _XqsF){local e8pTqNCm; 
   {
   }
   newline; 
   return _CNb2rrg; 
}
A(_4G){local HeCq, _GfE5ABt6u1, _dz1AA6Tkq, cD, _M; 
   printch 708; 
}
_0(_LkfNv, _DzO){local _DT0HNMM, _h, RisS8Jy8M2ytN; 
   newline; 
   newline; 
   {
   }
}
_e(KR7, DF7){local n, _e7XsIMOXk1i, _iLldDW, h; 
   println bC; 
   printch qS; 
   {
   }
}
_whb(_RG, _loALMu){local _wP, _wEFdlv9uD9hS, _4; 
}