// test_200_37.B
begin
   {
      newline; 
      print !7; 
      newline; 
      newline; 
      newline; 
      println udnHW_sVgvof; 
   }
   while (443 * _fS)
      if (X0fRR)
         {
         }
      else 
         _bWIUUTDz(); 
   printch 04; 
end
N(P, _oPN2vVr8oSF, G, _$$H7Wydz, _Oimp3A, _kzrt70e, AdWvCC, _Kois){local kz0PX, c, _ibj, _Ik6$zd, pj0; 
   {
      {
      }
   }
   return !(mXN < _iM5lJ); 
}
HK_M6icUbwFe(_d8T0SWEhXMSe1HuG4cE, _YUYPd){local _WrSwN; 
   println 174; 
}
_1(){
}
K(_wQjX){local _EXaIQc9Q, _EbQ3m, _RGa; 
   {
   }
}