// test_800_34.B
begin
   while ((_ykg) && (!074 && !_lp))
      ZGN8WBG5C := 326; 
   while ((_jlK) <= !233721549)
      while (LJ == 03042)
         printch _4; 
   {
      println (_uX$pJcU79AvDEETg) <= !29760074; 
      newline; 
      print (7495434) <= _nCzK_5; 
      println veBo() <= _K; 
      newline; 
      printch 99; 
      newline; 
      printch 693299; 
      _XFpvH(); 
      print 8433; 
      {
      }
      newline; 
   }
   while (_5(4379) && 4)
      {
         while (!62 - (7862))
            while (NDv_AXi(015) <= paDE6(373290109 / _QQqvVtfi7Qzg))
               print 2; 
         {
         }
      }
   print 62 - X_olU(); 
   while (704 && ((_rHex + !9) * d()))
      _$l_ := 5246; 
   {
   }
   printch !9 * !10; 
   e8 := nIi0; 
   {
   }
   newline; 
end
Oa(_Jr, GKqP, _Sr, N926J, evU, _V, _UuxzF7R, _$KfzYey0NjGpzb, _DC3jeG, _O, _daP9f){local YuJmy39, _64P, _bzY6, dB2J, I, WUn4e_eYJ0, s6UlQShR1; 
   print (_9d$5la(5 / 19, !_d9ClopA * 7647, FZ7NqiWuWh, 126353) + _Pr4(!vF || _F1$iOvK(!531 / 851), 8 == XN, Qc2, bM, 222 * _D(c), _2bD)) - 1; 
   return (_1TkV) && 86; 
   println !!_bf && 117645; 
   while (_k() || (_iIQcPVAk2LaIOR))
      {
      }
   println 658 + IA2O4T(); 
   while (6)
      newline; 
   newline; 
}
Fc(_J, _XRs, r, I, T){local Lq8, _z, _5rlDtV$; 
   println (_CvczkQi <= hWYd) == _P2; 
   printch CZ2X; 
   print 7; 
   {
   }
   return C5MkPjTGK() - 194926; 
}
_81z(E, PcJ, widY, _g51, _HUEi, l1AYin62Xf7J_ok_mUM, _Pwu, _h8, b, NnalX){local YU6W4t, r, _EMXdC2a, _4qWu, _fC2w, _G, OKa5; 
   return 48; 
   return _Lh7qh3a7_RG71x4; 
   print 3; 
   printch B; 
   newline; 
   printch _3 / _JoC; 
   newline; 
}
NHQgO(){local _zu; 
   newline; 
}