// test_200_8.B
begin
   while ((dZ5t0wW) || _Qa(06))
      println 57 < 70; 
   NY := j7tcVv; 
   newline; 
   print 569037; 
   newline; 
end
l(_VRr, _WKe3P4HHKsw, ZFvKEMQ, XRIyP8q){local qQc, _tRxxG0wwVRyfc; 
   _oMzBnWG8_k2(); 
   newline; 
   print (1) * 34; 
   {
      while (6569)
         {
            {
            }
         }
      print HT6y; 
   }
   {
   }
}
_XS0(_t$n, WYWv){local _xD, D6XC, _HV, lFi; 
   newline; 
   if (9)
      printch _xT4; 
   else 
      {
      }
   printch TF; 
   qYNl := t; 
   printch 75; 
}
YzBZJ(){
}
_w0(){
}