// test_200_5.B
begin
   print (09722172) || !(NdY() == 9034); 
   {
      printch 78 - !_m; 
      newline; 
      newline; 
   }
   print !7163 - 1; 
   while (!89 / Hqg)
      if (536)
         printch YH; 
      else 
         if ((0865 * 3) == _E7j)
            {
               {
               }
               println _MrlkMY; 
            }
         else 
            newline; 
   newline; 
   return 72 <= (uJ && 7821); 
   newline; 
   {
      newline; 
      printch 1665708830; 
      newline; 
   }
end
b39(){local _i; 
   {
   }
   {
   }
   lRsz(); 
}
_wfV(){
}
_x(){
}