// test_400_7.B
begin
   newline; 
   if (!0 == _2_N3X)
      print 2; 
   else 
      newline; 
end
t(u, _MSG, K, _I0, _zX9dMF3b$, _m9C5OpmUi3, _v){local j7n6r, _Jxdn9$xVE, _Xh, C, p_zAb, _gK, _m, rmg; 
   while (3 < _hm77uMsgTvatbHAN)
      println 647 * 9; 
   return !iFE_wuZTZXkThM$kYibAn() == !_z; 
   print (49) == !(_oxQicJr); 
   printch L0vMrxGtg() == AVD; 
   newline; 
   newline; 
   while (DIdysGa)
      if (2111 < 8)
         {
         }
      else 
         println Dxc; 
}
_6v(E1){local G01, _Z, __1; 
   return !!(cON) == 4; 
   if (__a)
      newline; 
   else 
      {
      }
   print !6085895; 
}
_w(__, P, S){local _Iz4y3HU, _G; 
   while (_AApL)
      {
      }
}
FX(a, _pit){local Hjc07; 
   return bJxj; 
   newline; 
   {
   }
   printch CnG; 
}
TtuUa5(_gF5, n, _D9){local _R1, _j; 
   return MD; 
   _pL := 5; 
}
GHe(){
}
NQh5v$VOs(){local _3SFCJ; 
   println 9; 
   printch _qj - 854; 
}
_l0S2rzmRuovo(){
}