// test_200_4.B
begin
   while (2669 == 63268)
      newline; 
   while (mGV3$E)
      {
      }
   __((0211) && 9, _5mHp9K, 799); 
   return _lsu; 
   newline; 
   {
      {
      }
   }
   newline; 
   newline; 
   newline; 
   newline; 
end
NpG(){
}
_H(_97kfAu, _rYeYZ, mM){local _r, u, _rOM, ARzVRD9xKt0AmKYOIyb3wF6; 
   return 9355 / 0463; 
   print _1g; 
   while ((616) / _K)
      newline; 
   _C := 8; 
   newline; 
}
_j(k, _EeTofYr){local _j1, i; 
}
_Ut(_U, z){
   newline; 
}
u(){
}