// test_400_36.B
begin
   while (((_B() - 458) && 0) / _Xy(4))
      printch !!3157 - (!780); 
   if (ZESlpW(!erM() * cI6(), _OF, _k == 025435546, _WF7u0, b6) && !vYzqNjkj(_Jo6jYNYFldS))
      _g5w2C2YZS_MnJWc3XTRK := 699; 
   else 
      return e3m && 0786; 
   {
      while (HcYJ)
         newline; 
      println hVJyFf; 
      if (75586)
         if (stxdOpgA0zXyjqwMuGHb2QUy)
            newline; 
         else 
            newline; 
      else 
         if (4)
            newline; 
         else 
            {
            }
      {
      }
      return 4040; 
   }
   _w(); 
   {
   }
   _wgTM3op0zqUBu(); 
   newline; 
   newline; 
end
_uukYXS(m, _85KWu1dp1FwCe, da4v7u4, s, w$INkvq){local yt, L2, _HOR71Q, TV, _QCIsR, lUDQ$EI5sZ$Hk, _ni, _hwTh; 
   if (ln(_X66M2rrx$d) < 3)
      println (xD) / !25; 
   else 
      return !(4) == TmsP(S6qxzR); 
   while (379)
      {
      }
   {
      if (!_Y)
         newline; 
      else 
         newline; 
   }
   return pJ6 || qS4F; 
   return 8 + _l; 
   println 08; 
   {
   }
   Czy9m := 0; 
}