// test_800_12.B
begin
   if (b1RL(8010 < (S), 8052755, 29332, sA$XrqQlYi) == 43)
      newline; 
   else 
      while (25 <= !!64)
         print !ve((9)) == 3786; 
   print !556981631; 
   l := 469 * (!59933 || !!!_pDPg); 
   newline; 
   newline; 
   while (6)
      {
         return Idv$ + _4TN_oLxXh; 
         print Teq; 
         newline; 
         newline; 
      }
   if ((!W6P() || (_694uBQP)) <= 2347)
      printch (XCdia) == !3; 
   else 
      {
         return _A; 
         printch k; 
         if (_fIdGo8)
            print 9; 
         else 
            return 93; 
         newline; 
         newline; 
      }
   print !(!_5aH / 2991) * bK(aPG); 
   return 455330 <= (_Z); 
   if (S)
      {
      }
   else 
      printch 318760; 
   {
      return !((80)) - m; 
      println 2538544; 
      newline; 
   }
   newline; 
end
_0GuWup(_PbtXTZWtM1N, _hTdMmgQwH, _9a, _4WKw27$sVpNfj){local _n, _Aq, _9sIzg_0XEMYQiQ, _KdS; 
   newline; 
   newline; 
   if (68 == T3aFaFZSfw)
      {
      }
   else 
      if (PRRZ2y)
         {
         }
      else 
         newline; 
   while (9283851)
      return 1666; 
   {
   }
}
__6(_9fX, _55i$7, _b7OdC3, _AQLz, n, _Bq, r, B, _yV0UbSbO3Kbu4JbrDVLrHTwge89, P_ya, _juJXjc){local NgQy5UEb7k, WDuO2ozE4, _$gP, Z, _3AQ, _4, _f9, _V, _nE6DLCrNqfMdHhP; 
   newline; 
   {
      newline; 
   }
   return !_4xrcioKu(f) && _tpXZt(); 
   newline; 
   while (_RJIymV(!_Xh0s, 05) < !_A())
      while (!(_zN$TJKUH / 35) <= 640)
         _6EvBJ6z := fcQ1eOzaFCuRNC; 
   {
      if (76)
         printch 2; 
      else 
         println q4; 
      newline; 
   }
   printch ezBLJmkQEy / 756; 
   print !623; 
   print 2; 
   newline; 
   if (568655)
      newline; 
   else 
      {
         newline; 
      }
   newline; 
   {
   }
}
LH2cUfK(_fqfiTxID, _y25){local _R, cJ5lEymlS6wuCQ, _XAL, _Gg, k9_XvzA, _8, pS4B, N, _H7; 
   print 08 * Grk; 
   printch !325 < _ca_eO(); 
   newline; 
   _uGd := 8069; 
   {
   }
}
OT3vbD(_UM42, _jq71$0t, XcY7yGJd2){local _z, Fex; 
   newline; 
   print o9TC; 
}
k(){
}
_KI1(){
}
_mL(){
}
_kK5hUQf(){
}
z52o(){
}