// test_400_22.B
begin
   printch tbBGf || Pnf8xACT(_N + t2Y); 
   if ((4) < 04695929)
      {
      }
   else 
      print V2; 
   if (_Ic(5, _Wm, 08288000) <= (0395))
      println (75557705) && 3; 
   else 
      return (3288) || 6; 
   if (ahOjf7G)
      print 662; 
   else 
      sW(); 
   {
   }
   newline; 
end
_DQaK(z3, fd4k, J, _1Cd){local _19L, _BS50ay; 
   print btc6Pjt0(w5i787RN, K0QxpYeIeXG) || (34); 
   newline; 
   println J2WR; 
}
ko(_icp$ADT, s){local hWg, vnuIw; 
   {
      print 049; 
      newline; 
   }
   println 19; 
}
_rM(H){local YohaEg, jZYi, bI; 
   println (91) / 6786; 
   printch K2; 
   while (47 && _fXzIYlmz)
      {
      }
   newline; 
}
_TUaH(_m){local _flRA, W, TF; 
   {
   }
   print UiDym; 
}
pPcgHa(_ppE$tj, _aro23){local _2ACr6, _fzjG; 
   println S; 
   print _vnyM((_e1S)); 
   newline; 
   _eQ$IP := _HpX; 
   while (178)
      if (A)
         {
         }
      else 
         _jiTvFgd(f); 
   {
   }
}
_TDvy(){
}