// test_400_3.B
begin
   printch (_CDg + 24576013) == _z(!(070), L); 
   return AgS(989498, 2580643) == !g; 
   print 46; 
   newline; 
   printch 550; 
end
_fSGt(YEwKxP3, R2vSlu){local hR, _nn1CvoI, _c3X, bVY, _MV4n; 
   print (_xVJ(v3kR(212) == _tPeX60, Q(), 8519, _V3h, J) / _wXLQ(3307, DxC, 5)) * 2269; 
   if ((925) * !_r3l5T)
      if (93)
         {
            qy(); 
            while (786)
               print 0907; 
         }
      else 
         {
            print E(_chrs); 
            xx(); 
         }
   else 
      while (_bwcw0Wco3uPqzeU + (vWD8TN9))
         {
         }
   {
   }
   while (_LP75)
      _R := O; 
   {
   }
}
_$c0(_r, m$, S, IyP9, xA, Q){local E8, _9, _FJBEhM, K5g; 
   _8K := _r; 
   return _0; 
   {
   }
}
_haFoARWJ(_qSj5EvR44){local MAaXwH$aB, _TZ, rRuexRhOWDO, Bey6; 
   print _9f; 
   while (!9 * P)
      newline; 
   {
   }
}
Qgkx(){
}
UtbEhx(){
}
uSSC(){
}
U2ZhT2S6KiAV(){
}