// test_800_5.B
begin
   println 554225 || 6416; 
   if (_tM)
      {
         println Gm1 && _x9(); 
         print 8 <= !_ZNk; 
         print 030300 / 5; 
         {
         }
         {
         }
      }
   else 
      return OR == !(4 - 146048); 
   println !(90 || 9) - s4(V3HnkN0f06Rn, 587937); 
   newline; 
   while (_Y() <= (G0Ro()))
      println 930 == !_ki2F(); 
   return 25299771; 
   while (7 * !_ij)
      {
      }
end
w(H_xEUSyDkevnz, X, JL9HwUx$fwj, _NO757, _b, tlmWef, _j_PbWG$w$GY, IbSYUs3b){local _cwYsgENrAy, _YL24pjVY$jhLl, _rE4tV; 
   if ((_n) <= _N55(z))
      print _P + (843); 
   else 
      newline; 
   print _C(bDfqe) <= 8; 
   while (976 - vexaY0hEmLhj4)
      return 160 / (091); 
   print 704 && !5; 
   print (!Rq) + rJWnr; 
   printch !!(_dwl$Pxd5A && vL1) <= !801711; 
   print _hQuIukLk6 - 914899; 
   newline; 
   newline; 
}
_Nh(B, dKHP, rinuK, nd2g, qk, _RQh9dcng_B4pc, _nfW_){local _lB, _q, _5cvF, _H, _C1TY2sGP, L, _pUe; 
   while (C1KWrt(_p, 71992689, _P, _GK4VS2B) <= 31969)
      newline; 
   print O; 
   println _s2E(125 * 92, eRCr9h) == 567; 
   return 5; 
   printch a; 
   if (0797885 < U48mjbwtt)
      while (lbbKQ)
         {
         }
   else 
      print _l < !ka$47TDR; 
   newline; 
   {
   }
   while (_LS)
      print 196292994; 
   {
   }
}
x(){local I, H, _42n, X, _M5, BgQ; 
   println !yJ * 13928; 
   while (250862186)
      newline; 
   if (or$3syb1qU)
      return _eb$tb0E; 
   else 
      print dA; 
   newline; 
   printch Vq34PF356Jt9S; 
   newline; 
   {
   }
}
G(aZM8y85, IeUxMbd, _kB, n){local C1V01j_; 
   print l; 
}
Oq(_c, _e2Om, _a0pvb, ZouwGbul0VW5, SSt7m){local _iX, dj; 
   {
   }
}
g$fP(k0y, g){local kjW8g, ir8; 
   newline; 
}
sDg(_j, rr$){local _Ch, _8gr4NJ, f, G72; 
}
_y(){local DW3, n; 
}