// test_200_30.B
begin
   vEKGL := !(19); 
   return !_l <= cbv; 
   print _6gT(740 * 99, _SNeDk, CsMx) <= (YT); 
   {
   }
   newline; 
   newline; 
end
_NF(_B, _X, mK, _0$){local x$oQz, YGzd; 
   a(); 
}
_1ue_(_t, o){local Q, _HeH, Zn, _zQ, PDea, AaqgcCsJa; 
   while (79203)
      newline; 
}
GV(_u6eb){local Mwwv, H_BQ$9XYCK80j; 
   {
   }
   {
   }
}
tM7b(){local JwWVTI, Z; 
   newline; 
   newline; 
}
STjE(){
}