// test_800_22.B
begin
   newline; 
   while (87)
      g_hdjj := _fX2Hjp * hE; 
   return _gIj(133418 < (Yv)) || _P(4288); 
   print 8; 
   println 7167134; 
   if (1)
      {
      }
   else 
      {
      }
   print 9158; 
end
_x_34x(_7vJ, B, _7, Z3EYhV, _qfUA71, bBKtTExa9zM, _cT, GzW){local D, SwI2i, q, OwQSioxY, LQTkJOb, n, fN, _AH0; 
   if (!!A + 49)
      return vSV() * 023; 
   else 
      FZ := juSTMfQ < 41; 
   _Xca := (43339) <= 0; 
   println 255740 + 37; 
   {
      return _D == !28; 
      while (ty6p < 419021)
         print LgsA <= 730; 
      u1SdOFyKkpLgoay3WR9dOoiKpz := 8283479; 
      printch (Y9lwQ); 
   }
   if (((_Zo == 598761591) + 4) + !41233)
      return !!89 < !(1); 
   else 
      println (4 - 729674); 
   {
      printch 431104 - !32; 
      if (0 == 5)
         if (4 < (6495))
            while ((_VkLG) || _wKXmmL57)
               println W; 
         else 
            println 4; 
      else 
         return 783941; 
      NE := sO$(51508622); 
      return 055; 
      newline; 
      newline; 
   }
   _MG(); 
   _v := 1; 
   newline; 
   println 4; 
}
SlZmTo(jLlXC, _O, _AM, b$, NX8, U){local k, V, _3h6oD3I_, _Z3$t, _vy, B; 
   newline; 
   newline; 
   print 07 / 4; 
   newline; 
   return 1207017305; 
   {
   }
}
U4(SJ3q68z_SJZe, _SQ7p, P2Tm73$, IQ, _z6, _gb78SP, zgGS0S9){local _h, b, SLIVJZQ, _LMY; 
   {
   }
   println _o <= _V(); 
   while (I)
      {
      }
}
xssOhq(){local _7DIrZBTwLgO6; 
   return !5813 < (_GI); 
   newline; 
   {
   }
}
_pY(_cY, _n, _X48vs, _2Bs, Dx, _p){local _K, Lobn7, eTO; 
   printch 762 + !ziRk; 
}
_3rCDEL(_jyksH$QWs, C6){local yuq; 
   newline; 
   print 1; 
   {
      {
      }
   }
   print 472675 * 5; 
}
_uJ(T, _Ya$Y, _U){local jjBS, _91Ma; 
   {
   }
}
_EC1F2pi(){
}
_8$Jf(){
}