// test_400_1.B
begin
   if ((78) || _1())
      println bSGEhLK; 
   else 
      newline; 
   {
   }
   print _Q; 
   _Q9euG0VZJ(75, _vV); 
   println _hZANffZ54OD29A2e; 
   newline; 
end
Z40(_y, io, PB0G4, _rEFA, z7D$_, J9){local TAM, _i, _7, _zOY, _3z, _EsC, gp6, Xi, U, _d2, _U16Af, _VxjJ, ZoD; 
   if (31822 && _fg(DRXi_HQz34Qv + _u7yaZ, 0747, 77, _E, 6, 512, 39, 26793))
      print (038 / (!(32) < _0O01Wyo89DW())) < 606; 
   else 
      C4qk := !!!!(77) - 9001611; 
   println !!(962117); 
   {
   }
   {
      {
      }
   }
   printch 768795; 
}
M(_hMd0T){local LaZ, _8, _a5a; 
   if (AQ3Zc + 5)
      {
      }
   else 
      return 6; 
   if (2361994)
      {
      }
   else 
      while (_Gubd)
         newline; 
   println QF; 
}
_RnmSh3(eD, _A, z_af){local _j, qJL, k, sjN7xD46ECHeN, jL4Ldem, _93wo; 
   {
   }
}
_oaOu2(){
   {
   }
   {
   }
}
R(){
}
Q(){
}