// test_200_13.B
begin
   if ((((g) || _6rql1q) && 0) || 2512341)
      printch 61966137 + (80); 
   else 
      return _0OhbA$(); 
   while (_Lbz(!491 - ybKEqNeQ, cC, b, _3_6, hF, 89813) == !_HM())
      printch (735630 - _NDiN) < 393; 
   newline; 
   return (qz8UtXk) < 3627; 
   {
   }
   printch 0; 
   newline; 
end
vWs(){local _3A; 
}
_Nc(_Ie, N){local _hAmdma; 
   {
   }
   newline; 
}
_0(){
}