// test_200_32.B
begin
   return pB; 
   if (_LiGp3$RD && _h9)
      print 2121225727; 
   else 
      if (_vE3fx61fK)
         A(); 
      else 
         printch 953; 
   printch _O5$kpcKS8 / _5O; 
   {
   }
end
_hAU(){local L8z0VkTGwHA, _d; 
   while (_h2vAtYWwG)
      newline; 
   while (7)
      newline; 
   newline; 
}
_CD(r3GHC){local C0GUtXnPf$Waw; 
   print 435; 
   newline; 
   {
   }
   newline; 
   newline; 
}
eh6Z8GyUx(){local _NspI9; 
}
O3Wc(){
}
_HR(_1Qw){local CYnf; 
}
_8fYt(_u0X){local hk$cJ; 
   newline; 
   {
   }
}
Ch(){local Ox; 
}