// test_800_25.B
begin
   newline; 
   print 4837195 && !72; 
   if (_i(!99 == wK4(2), _H == ((62 - 6137)), 412448, 7558, 214901802, 5242, 9 <= 355) < !(7004))
      println !!_Un2lJ8z0() * !!(73); 
   else 
      println zt(_H3qH) - !gvF; 
   printch (84) == 01878; 
   print _CE - _qhbVg; 
   println N_() <= V(); 
   print 36 && 68; 
   if (75269569)
      {
         {
         }
      }
   else 
      if (_ZMF)
         {
         }
      else 
         newline; 
   if (NPkpVw7B - 03)
      while (_8r < (_g3))
         {
         }
   else 
      return 1895495 <= (mq()); 
   {
   }
   {
   }
   newline; 
end
r(BNZk, hB, _GlR0w, p1, __){local LMIL, _PuaM, _h, _oS; 
   if (68 / 05503)
      _Re := 0; 
   else 
      return !!(ZM < D$VMSb) < qsLD; 
   while (6037 || L)
      newline; 
   while (364 * pw9ADg)
      while (33)
         {
         }
   if (_b)
      {
      }
   else 
      newline; 
   {
   }
   {
   }
}
_j(y49naD, r8Y1uGj0EFas, _UNE, S$, UYOdu7, C, _k24Boys, qOP, PV0, P){local _$Y, M, _EL_ELefnAK, c7, nL$; 
   printch 164 * !_rPMBy; 
   if ((A5fugD) + _n)
      println !78 / w(); 
   else 
      newline; 
   printch 8 < !94111; 
   {
   }
   return F9VqPET; 
   _6$JZ := _p; 
   newline; 
}
rNdC7ph(_JUjELKZb0, _Q, _ob, _krrXF, _CueHwK, _4E){local u; 
   return 4465; 
   printch 21; 
   newline; 
}
_D(__H00FtW, _FBEYX, _pL){local _1, _i2X, E, gykfn3, VVM, _y1t, _xV, X8ZY; 
   if ((lLm) / vVq7k)
      print 4 * (_Ml); 
   else 
      newline; 
   print 1; 
   newline; 
   newline; 
   return _S; 
   newline; 
   newline; 
   newline; 
}
GLulJ(U9){local _KKnm0qr4z9_, k, p, x, _c$q_, H2WOSpT3Ag, U, _yq$2V; 
}
_NOP(){local M9, _TYPG, dcU5Fx3BVNX; 
}
_kFi(_nn, u){local G; 
   print _Bg; 
   newline; 
}
K_(){
}
_7(){
}
IILaOE9(){
}