// test_200_48.B
begin
   print _PSqI(p, _ZXD, 8848) && (_RttpMw66QphwpPXa); 
   {
   }
   while (ZdxJ(1) == 38)
      {
         print (0547) / !_R; 
         newline; 
      }
   printch _a4JWfW; 
   printch 07; 
   {
   }
   {
   }
   {
   }
end
z(_z3p1wti, _P, B, _PJEt4yJ){local _$D, _fasj, BPzTMGQ; 
   if (62968)
      {
      }
   else 
      if (3)
         {
         }
      else 
         {
         }
   printch _rlH95h; 
   newline; 
}
_9K(){
}
t(_waD, G, fR){local _Z4fRcn; 
}
HLXk(_vO2ria){
}
_n(){local _qVazslg; 
   {
   }
}
_Nxl(){
}