// test_400_47.B
begin
   return _lThA(!9, I) < ((_KN1qCqp)); 
   {
      if (9 < (!66))
         println 8; 
      else 
         while (!_D - (_R2Cz4))
            _qldEO5k(); 
      while (9949029)
         {
         }
      println VIg; 
      newline; 
      printch _q; 
      newline; 
   }
   printch 159 < (1 / lmF); 
   newline; 
   print 6 || XQIvc(8932 || 6); 
   while (21332687)
      print 315 || 1506; 
   newline; 
   return 3; 
   printch dkIwEtFKsktI6yBho2IZ; 
end
_FadAWRIry3qanowN(_70MM, _5z){local GqHG, z, P, _PKRr5Ctia9Sw; 
   {
   }
}
Pl(U, _QH1){local Sdw; 
   {
   }
   if (zNCappT(_3d4Q5oX0zbDALdl, _XJgL) * _ggF8FY())
      newline; 
   else 
      lq := 49; 
   {
      printch m - 96; 
      newline; 
      {
      }
      newline; 
      if (GK$ - 9)
         printch 287973; 
      else 
         newline; 
   }
   print _GwJ_LpFCaLbuCLLO3x; 
   {
      newline; 
   }
   newline; 
   {
   }
}
_QOUT$Sr2Vz_jIzM(Vb_r, uLQsW, _A63e, QP, h){local _4XAygjccKLmmY, _ZmCtL, _AMBTPm41, _YE, _yk; 
   newline; 
}
_6GCn(){
}
rN2Gv(){
}
_W(){local _DQ; 
   newline; 
   {
   }
}