// test_400_34.B
begin
   printch 53; 
   print !(CZ) && !!Bf_nCq(zE4nn); 
   return 28; 
   newline; 
end
L8oqm(u0$, _abh, R, _iu, _HqY, M){local EbXHom, xw; 
   newline; 
   return _lkU(025) * ((56453696)); 
   println _EKGlj == !89; 
   println !50814 < _JWHUcG03; 
   newline; 
   newline; 
   {
   }
}
nV(_xd, _RBCnBU, _$81, Pvi2CABZJ, _V){local k, s, BGdLVBCOF, _4, _3, __VrcLKXP, _lFeJ; 
   newline; 
   return Wvgbnc - _s_; 
   if (3)
      {
      }
   else 
      {
      }
}
Si(_x, tQCW, tzeNvr, _sHPf){local _$yucU_twc, _GWkjJw$, _D, w2u3Y; 
   print (GnJuT6) <= 19; 
   {
   }
   _3Ot := _sEne_HlkzQ1; 
   newline; 
   printch 016; 
   return _tyGCKmt == 0774788; 
}
_Bjp(_gU, Y_cj, CsHnUWoRmxyYE, smy){local dEn, IQlS, jU; 
   print 85784; 
}
_sk(RT2I, _y, w){local k6aYEmvLGst; 
   newline; 
}
SP(_HD, _NM, N){local _2G; 
   {
   }
}
SQW(yLJC){local _k; 
   {
   }
}
Js(){
}
K5ilM(){
}