// test_200_2.B
begin
   {
      while ((725 && 5) && 443461)
         newline; 
      newline; 
      printch r$hDmBBG; 
      print W8hGNsx; 
      while (518)
         newline; 
   }
   x((k) / 63, lyIGpb0x9T); 
   while (!!917 / (478520 < !!(5)))
      return kNcu; 
   print !8393 == _pOVWTCfPnc; 
   newline; 
   {
   }
end
_Z4kgF(zrxhCLsip5, _La, cH, mXdrF, _3){local _m9, _ubZD, _HL; 
   {
   }
}
_kzSQ(_k9gAlTF7gty8$2Be7e5){
   {
   }
}
z(){
}
_f(){
   {
   }
}
_z(){
}