// test_200_1.B
begin
   if (78273)
      print (5847) / 07; 
   else 
      if (u)
         while (s)
            {
            }
      else 
         newline; 
   newline; 
end
_o(_u, _a, F, dvJ2ay5){
   if (R((50) * !810913, PfxIRVEcKalu) - !0)
      {
      }
   else 
      return !_KU / _79J(); 
   while (nIfVE)
      while (08634)
         {
         }
}
d(){
}
_R6$u(QLFKH, _9Ff){
   while (2568)
      printch Q$tu; 
}
_xS(){local ad; 
   _pcEkBwKW := R7ZY8CfJy; 
   newline; 
}
Ywvw(){
   newline; 
}
_00(){
}