// test_200_14.B
begin
   newline; 
   newline; 
   newline; 
end
_$(_i, YO, _TJOun, bqTYGI, BX, _v){local _6H, _e9, BA, uXl; 
   println 719; 
   newline; 
   newline; 
}
eu4p(_vb, _Ig, oQ, _pLvCUd){local _FgKt4pGsnDU, WdI, UAXSBNt2MIv, aM, l5t, dj, _DVX; 
   print _vnT; 
   print 8 * !262605; 
   {
   }
   newline; 
}
lzS(_sbYp, _m){local _O_uAW, _aZK, _sN6miEXF, _1d; 
}
_v$73SLZ(K6xD120, Go){local _TL, _U; 
   newline; 
   {
   }
   while (RIu)
      {
      }
}