// test_800_36.B
begin
   println 6 / !!80; 
   {
      B8 := 31420789; 
      while (_vZPi)
         newline; 
   }
   return 2 < 86; 
   {
      printch 2 == _WQ(); 
      print f; 
      while ((!(QeFbEDT) + 983) + (4))
         {
         }
      {
         newline; 
         {
         }
      }
   }
   if (J3g6w)
      {
      }
   else 
      return 94; 
   newline; 
end
_zB(Br, mTaAg, _Dp, _9_es, _Cn0_iDy4ot, W7, YT, lwO){local eZalbG, llFi2, _f35O7_v2qXrV, xo, Ma, _iQK9u; 
   return !6 * !!!Of; 
   print _yA(!51946 < _n7gVi(2877, 2, gg), 2162 <= _G, 5 - !794, 8334, yAdX, 84, _ma2t) + 794; 
   H8(); 
   {
      while (_GWDaC)
         print 0 - pn5w; 
      if (2266)
         newline; 
      else 
         {
         }
      newline; 
   }
   println ((DF$Cg / hFg) + !_b6dgqjHdNRx8gn) <= _D; 
   if (2902 - !IvuZldf())
      return !1 + 31783; 
   else 
      {
         _uVohO(_PAz5t59qK <= _fiPq, 34, 5); 
         newline; 
         {
            newline; 
         }
         printch _s; 
         printch WT; 
      }
   if (_me4h < 5)
      return (_wj + gY) * xwdMKQ(drkY7vnyvX); 
   else 
      print 4; 
   newline; 
   newline; 
}
kC(od, lhe5n, a4, _g, x, _lh, _f){local _ZnZ, _LMdn, QgHQ1Zic, T, gou, _joeJ, _wju; 
   printch Y3() + 0; 
   print 6966653; 
   if (_13N_7$nG)
      newline; 
   else 
      newline; 
}
_51(_G, _1PiO, _A, Tqf, t5RIp, D, _O, _By4tlFx){local _Vg, _o; 
   if (_T4o / !!95)
      println !725; 
   else 
      {
         print 85; 
         {
         }
         print 669930; 
         newline; 
      }
   print _h9; 
}
_6uQ(Ua_QfnN$, hE6lI, XrAX){local nYt9P, _F3dGU, _yhpIsXG, _N6PPo; 
   newline; 
   return 539; 
}
uuGf(_Xhg2EtOd3d){local __; 
   return IgZ6a7; 
   while (_K)
      newline; 
   {
   }
}
_a_iP_3L(_2){local _AsBNOt, _YoJH; 
}
DF(){
   println 0; 
}
_aA(){
}