// test_400_6.B
begin
   while (48 < 92)
      IR := _C8UjGmkg + _nlElLzu; 
   {
      newline; 
   }
   QWG(!(8) / 97); 
   if (_Ch - 904248)
      newline; 
   else 
      if (00816)
         newline; 
      else 
         newline; 
   if (z)
      printch 4906; 
   else 
      {
      }
   newline; 
   {
   }
end
_sYP5E(_wvQFh){local vRHTBCLFDGLcCG, _kJLFIk, _K, _pY6, EPpqAaDI2, PyKhHDBlTTm; 
   if ((75) <= 4744)
      println 704405 * !_mVtMOp; 
   else 
      newline; 
   {
   }
   {
      newline; 
   }
   newline; 
}
_4(INNF, I2YEzPo, nd, zFP34ilFxVz6JIG_T, C, _K, PXqb, MF, _I4pU7Y2Oe4, BLSck46r, BJMd){local _lBFO8Zr, _xnvEZIt1xf, _qSc3, X6, n, j9l; 
   ALg$18eFT(!98, M); 
   return !051; 
   {
      {
      }
   }
   _s3MxxqPPn := BjbPRbyD5u6NxF; 
   while ((33))
      {
      }
   newline; 
}
a(L, rZ7, T_dnA3, zDfhV, _MIa7X){local qdqhdmkq3_, CTRpM; 
   _Z(5 * _kVA90NqqU8); 
   printch 7342 < (g); 
   if (9)
      newline; 
   else 
      {
      }
   printch 626178; 
   return nYv4eI; 
}
_7JMiTkz(){local x5XcmL; 
}
Zlme(){
   newline; 
}
m4(){
}
GD(){
}