// test_800_18.B
begin
   println (_a5T2QpL) + (_hU); 
   while (8 + (56))
      while (_wt(ZZL) + 250914)
         print _v; 
   while (!2623 - 2)
      print _E; 
   while (Znyu0mKa$IC() < Y8dnf)
      if (87)
         {
            while (55215 || _QSO)
               {
               }
         }
      else 
         if ((Am <= 4) <= F)
            println !00; 
         else 
            Wb(); 
   while (2)
      {
      }
   print _B; 
   newline; 
end
clOE(H8, _1vP, i2QfLdkr, Z, _k, _9GoqfqTiy, bku, _wN4jznv, OIzO){local n5pSb, l, g, F; 
   t := _H / 096; 
   printch TG_r3Z < 39722; 
   newline; 
   if (239717900)
      {
      }
   else 
      Wch := 50; 
   newline; 
   if (7)
      newline; 
   else 
      newline; 
}
_H3(_DGPv, wE, _L4IuH, ztOpY){local tf, e, __; 
   while (L() * 998844)
      print 9520 <= 00; 
   _L4TOL(t4v(63587, 86618) + 1006539, 33767, c, (Jd / !251565414), 4); 
   {
      if ((YV_sVkh04) < 4534)
         {
         }
      else 
         newline; 
      if (HR / sm)
         return _86; 
      else 
         println (813) <= (5); 
      newline; 
      printch 73; 
      {
      }
   }
   {
      return 0963 || 69154; 
      printch NG() < (447353824); 
      {
      }
      printch _G; 
   }
   newline; 
   printch AkW; 
   if (_9rK)
      newline; 
   else 
      newline; 
}
_OvNI1(W, R67, _iV, _76iqxrG, _yy, xxY){local _6, NFn, VvFj, nAwfAyaTb, _nT; 
   newline; 
   while (N() && _0q2d)
      {
      }
   return _D8r; 
   if ((_wyd4kC))
      printch _O; 
   else 
      _ZXE := _d; 
   newline; 
   newline; 
}
_amdgg(_8, _YPt7s){local _z, _ihXQ, _uW4gpmTfz; 
   println T; 
   C := 89; 
   newline; 
   while (7)
      fkqf(); 
}
kh(Q, bO$){local _Wte, _N; 
   printch 5 <= _DJZO9; 
   print _zJ; 
   {
   }
}
wE(_ihk, aTWa1V0hJx){
   H(); 
   {
      newline; 
      {
      }
   }
   newline; 
}
_ip(c, GAb$Q, A, A){local GByhn5I, oQOhblrat; 
   return _n; 
   newline; 
   newline; 
}
_Vhu(){local vop5GVrqa; 
}
_jRtLa3hB(){
}
_11pdimS1(){
}