// test_800_23.B
begin
   println 1811907984 && (966 / 189); 
   print _02$ve(LVpra$Hlu(4, 212991, lfD, 31) - !o(MepTci), 82 - m, _YIbkVFh, _$CWXp, 4468, 821) + !!278; 
   return 92 == !810; 
   return 7 <= _X; 
   k8TzcnAPl := !gp42dAWe$W(8, H9Rg1aZw, 7110) + _ov(39562); 
   printch _Kw(1, 8) || (!!!(_ME) < _t); 
   print 4; 
end
_R4fJC_7(_ya, UXXItu, _T, WXwEFigp, _9pto, _L, _Qn, Km6OD, _95){local v, gzY, v, CaXI, _u, M6, fHUdYXgwWvo, _Vf, _ywBmE9, _y; 
   if (_GiigM8e(!Uj6 && tqLj, 6 / R1m9aKS8rN3TP, 80, 2, 7, 4621679) + !!_V)
      print (zAdtV(_uj3rX, 649 && gg$i, yu4Z - _I0CMBS2zT) == C5le) == (HmF(808872192) < _PsFdV1o); 
   else 
      {
         {
            newline; 
         }
         println 142; 
         return _11y; 
         printch 9 || XX; 
         println Bej; 
         newline; 
      }
   printch 1 || (O); 
   if ((765) <= (7590))
      println fGo; 
   else 
      if (vy)
         newline; 
      else 
         newline; 
   _d(87551); 
}
sU(Im1, M, B$){local IKO, _l, f, CdVWb9tQpe$3ZKiM; 
   println 7390 + 937; 
   println (64 || Y2FDW) / t; 
   while (9 == (30))
      return cUwe; 
   {
   }
   newline; 
   printch (_hSOWbpEL) && (_sX5ec1tT); 
   newline; 
}
_Jfn(_nQf7mhQl, _4N, _4, EleC8f, _R3Cx){local _U, DC, _KU, K, _O; 
   _x := nd$G; 
}
_t(A, _N17, sByPwo0KFtXhY4){local h68FBC, Ew, _ihAZ; 
   println el() <= (9); 
   println 615219; 
   while (66354545)
      return 75 == 7632; 
   while (QKdFe4w)
      {
      }
   {
   }
}
_5(){
}
_E(K9G$){local c; 
   return UQ; 
}
_$2pF(){
   newline; 
}
S(){local _iC, o6fbnEg8bcVgavq; 
}