// test_400_24.B
begin
   newline; 
   return 08132 <= (416116 - _TFa()); 
   printch 36592 || 639; 
   println (5 * _LtUGnRnd88) == Q1EHTt; 
   print HII; 
   {
   }
   newline; 
   return n - 602; 
   print _7KmVp9; 
   newline; 
   {
   }
end
_F1whh5CYe(_Xl, v, uQt, _u, Djm){local _obW8, _rfWk9j, _zgXoIx1CLSvCcy7t9Da; 
   printch _BCAnf5; 
}
_XK(_5B, L, _W, _lI, _k){local Z, YO4TlAG$3e, q7f3B, kg, Q, RbxpRu, _W, _vnzfh, _dSznqogge; 
   while (562266)
      while (726)
         {
         }
   {
      printch _$J; 
   }
   printch mx3W; 
   {
   }
   {
   }
}
Y(MVyR2h, gi, _vDr){local x, __Rx, ZISFg, K_; 
   newline; 
   {
      JEG(); 
      println uArLFL; 
   }
   {
      newline; 
   }
   println 26; 
   print 4; 
   if (_sLfHI37)
      newline; 
   else 
      {
      }
   print g; 
}
gm(p){local iVsso9v0fVT$C, t0VPR7Ae, _dxUJOiR; 
   return 0; 
   if (P - _eOmMWH3H)
      gQ(); 
   else 
      newline; 
}
pj(RHocTARj1r, _gHLC){local _zE5C, yUhMtZ; 
   {
   }
}
_k2D82(LQW){local a; 
   {
   }
}
_S(){
}