// test_400_33.B
begin
   if (!!(Gk() && !0989) <= _Qa0(9813))
      newline; 
   else 
      newline; 
   while (_C5 + !6308)
      println _ET && 07477; 
   if (918508 + !_k25Y)
      while (_c)
         print 666; 
   else 
      {
      }
   newline; 
end
nY(_Tdej, _jilp, _vfU, lb, _D){local __hpjE, ZB, _k3, _KCx, j, _7f5, _BFi, _Y, d_cMn, _W, _f1I; 
   {
      {
      }
      newline; 
   }
   {
      print JhF * 6; 
      {
      }
      return W; 
      println _D2DPMLRHR; 
      printch RgVFg_W64Dn; 
   }
   {
      println 96787557; 
      {
      }
      newline; 
      newline; 
   }
   if (jpO_CI)
      print !_sVx1k && (d99Bse); 
   else 
      println rusXNTSEL; 
   {
   }
   print _LN; 
}
_wFUmO(aT, _ql0oqt, nn){local EW8c, _yr, y; 
   _0W := g15; 
   {
   }
   {
   }
   {
      newline; 
   }
   {
   }
}
ub(_j_){local _m4, aUy, SaG, H, cHWr; 
   newline; 
   {
   }
   return _Q; 
   print 1; 
   newline; 
   {
   }
   newline; 
}
j(){
}
_F9qM(){local _th; 
   newline; 
}