// test_800_30.B
begin
   _Sr := !_WFXq(3 / ((311507514) < (_SPIDW)), 60826 / (_GrEKGJk6), fyxS + Nv, 6, 20, eY) - (gEb(i5jC < 1, 7, _fdre8Q, 99) < 6); 
   while (_Sm(8637 <= 67733291, 3825, _t_NfN) / 25)
      newline; 
   {
      _Fov := _l5C$m(ZPl(74378) + 1444173077, 39455, W, 1131517) || 7; 
      return y; 
      {
      }
   }
   {
      while (!!!XN && !!((_R * _UsCX9h_OqLYUtw6(xMSRI)) <= (_i$HQc)))
         while (39 + 6234)
            {
               println !12292; 
               gOvDlIiW(); 
               if (34)
                  println 5; 
               else 
                  {
                  }
               {
               }
               newline; 
               newline; 
            }
      print !!30 - 955554; 
      print pJfgN7; 
      if (8718044)
         if (yD)
            {
            }
         else 
            newline; 
      else 
         println _5hXZ8G3uE; 
      _ZYFV2q := p; 
      {
      }
      println _IOL4d; 
   }
   if (44 == 7)
      {
         {
         }
      }
   else 
      newline; 
   return !!b7TrR == _o; 
   newline; 
   {
   }
   {
   }
   while (0696)
      newline; 
   newline; 
   {
   }
end
kP8xd4(i2odBgT0P, haKxD, p, _p5txLIYYT$4, _Ir9n, bZ6, _a){local O97hCyMs, veTO, _f1vh, _nJZhN6e, _GOlqxaqO, _$vvNkTXWp, _5j; 
   print ((FA + !chLOXt) && (_t(205808493 - 6643, !58062, _a, _9qBAprT) == !215)) / 121; 
   newline; 
   {
   }
   newline; 
}
_G(bOp4VR, _rE, n){local _f0Ou, R, ab, F, eL, tSCA, _0qQ07iSEhG, cU; 
   _ZG := 110; 
}
b5(z_, HI0agU, _uAvd, N, _2){local Kc, DBhA2K, _Ap, _aEL, cQg, x8; 
   return 9; 
   newline; 
   newline; 
}
_3(_sSGj, E){local _y, B; 
   newline; 
}
_5(qSQZY, K$, _3m){local _ZoCV$_uzjb, _Z, j, _lHq; 
   {
   }
   newline; 
}
_gxTOzE1E(HTX$, _Hh2, _g, BqR0b, AW2X){local BTmpq, z, _TQd9e1Dd, _39Lp; 
   newline; 
   {
   }
   {
   }
}
SYsVr(){
}
f0(){
}