// test_800_16.B
begin
   print !67476 + (_J < !54316789); 
   q(_gHpqUXh(Qfqn0GiLfr((4758051) || _6O(a6, 45), cs, 96293945) == !_w, 5, 64) * !(1 || _w3Diz1), !FK * x(_eAI22_HFiGK97XNjJ8OK), !_wcyC1 && 2736, !_m(11 / 936, !_4_LQ45lnajR, _ecmzDa0bEnfgax, (_cXb), _r_dUb, x, 51, _bUZ) && !(5), !!36245910 == BU(7 * 4, 1857, _g, 9780012), 2883, (03) / 5, gWi9k, _1c8, 807 + 546, _0N, SFA); 
   print 54 || !!168290108; 
   while (Ex5dJ$q5u / p)
      qk(_qv(_o2AZSg_) < 4242138, _gr, I2dmo); 
   printch _Kh; 
   C1ZU2z2s := 30; 
   return !(_ssp == !(5)) / 515451907; 
   return 29 || 00; 
   newline; 
   if (6844295 * 96917)
      println 2; 
   else 
      if ((_WmTi) * (52))
         newline; 
      else 
         return (87) * _Pm; 
   print HR; 
end
vZo(r6, PmnArxOE, _gKHrf, B, _0tlaaXuQKmLo3){local Y, _$, _B2BLYTHw, ZC, _A4kfyAqZ5ifwrV, _kSNI1X; 
   newline; 
   newline; 
   newline; 
   newline; 
}
_g(Dcw, G, _b7U9){local _nN, Kxays, dpWc, _gp; 
   newline; 
   return ADc + (_PF); 
   while ((0943))
      _I := 564; 
   printch y0TY() && !_Z; 
   while (1864437)
      aNUs(); 
   {
   }
   {
   }
}
tLz6(_$, tiAwMiQ8Me, rAKTFi){local Q, _RB, _8paYl; 
   {
      {
         {
         }
         {
         }
      }
      printch y; 
      while (_I)
         {
         }
      if (_g)
         {
         }
      else 
         print 214; 
      newline; 
   }
   newline; 
   {
   }
   println OLItevOvml; 
   return 01; 
}
IUUe5rkm_GXbzFUH_8pLKocV4NmrO(DGFuSX, _JJA$2a_oh){local g, _4U, h, uNAl$W; 
   println b9NHL() < 103; 
   {
      {
         return 25734; 
      }
      EK := 7456 <= !kuMQU_uZ; 
      {
      }
   }
   println _iJ; 
   {
   }
}
_HTG(RQy$, _F4U6pmK){
   newline; 
}