// test_200_25.B
begin
   if (_LQiKS() == (7))
      print _s() || 0; 
   else 
      if (_UL3qEE7)
         _rpH(); 
      else 
         newline; 
   return _t(!T7 <= 3, qSf) || !si(); 
   return (yKLAMs) / !(_RkqOQj1); 
   newline; 
   while (7 * qtLzv)
      while (id_)
         newline; 
end
_Lx(_3){local v; 
   newline; 
   newline; 
}
_T(_p_PfuUZAC$, q, _Or){local W; 
}
_U7o(){
}
XJrK(_bVR){
   println 8; 
}
_4(){local xbX; 
   newline; 
}