// test_200_23.B
begin
   {
      newline; 
      newline; 
      newline; 
   }
   if (Qp$)
      newline; 
   else 
      print mk; 
end
_5ai(_h, _UZuDZ9, _SjgO, __, _PU1, Y0zy){local DM, _VSx, _UF4; 
   println To(_j) - !8; 
   print (71476) * 8174; 
   println _O(); 
   newline; 
}
qs(Q0uC, _z, g7t){local Ye5, JJcEiQP10c, p, _IHYyY; 
   println _tSg() && !Qqy30; 
   println !!754; 
   println _3_1; 
   printch DRJ; 
   newline; 
}
_fQ(){
}
ziOE(){
}
_TMZSwdma(){
}