// test_200_21.B
begin
   newline; 
   {
      if (_S)
         if (R - _zK)
            while (sJ7XM)
               newline; 
         else 
            println 05; 
      else 
         {
            newline; 
         }
      iiM := uv2; 
      return 50; 
      return 72063; 
      print ukzo; 
   }
   print (6) && jSih_GY; 
   println NeCeZpb43VIUVx(237) || (_KG); 
   newline; 
end
PkuFw5d(OA6o, _CI56dp6u){local XV, _KSVD, _rKVomZKioSx, cu; 
   return S; 
   {
   }
}
_1(){local _uX, K2czQv; 
   {
   }
}
VBX6RhR(){local fZ; 
   {
   }
}
Hb(){
}
A0Y1(Z2pKZkhYgYD){
   newline; 
   {
   }
}
_OS(){
}