// test_800_6.B
begin
   _jjIrd(pxT() && !_zzbt, _l3RU, _Qv(C), Hr, u41zcj && 948817, 1, F); 
   if (5680199 && 85)
      println 700 && !!!(9 || !290802); 
   else 
      if (5470784 - 1)
         print (Umj5) || _6(80, Lnh(), 4, 0); 
      else 
         println (czNa) - 2; 
   _z := 5970071 + _5(37); 
   if (G / !2)
      return 60; 
   else 
      _M := _$by; 
   return !4 == 2; 
   if (W9IAWgEM)
      {
      }
   else 
      B(); 
   while (ASMSqGTVw)
      newline; 
   newline; 
end
ohP(l, Nx01E, _k, _iwCa4JU, _pFp, h5G3S, _cvWal){local v, _JYm8aGk6, _vfciM6, DRPGwfR, _rBVUns, _8, _n, _SrP, _dn, _lUZW; 
   println dM() <= (_C(Pe2dq * 117632, _e) / !72); 
   if ((6417) * (0702289))
      {
         newline; 
         if (081)
            newline; 
         else 
            newline; 
         newline; 
      }
   else 
      {
      }
   {
   }
   {
      {
         println _r; 
         printch _M6; 
         {
         }
         {
         }
         {
         }
         return __9e0; 
      }
      while (i)
         newline; 
      newline; 
   }
   newline; 
   newline; 
   println _1XcOw4uJ; 
   printch 81 < 6; 
   while (_Vl2LZ)
      newline; 
   ap := 6; 
}
A(XYh_EuEBScUbo9gi1){local H2j, Typ0fblXxGWmO9FUvwd, dlc, _KX; 
   newline; 
}
_CC5(_0, _hm, _i){local _KRFn4Y1; 
   print dX5X; 
   while (!D3 < _L)
      {
      }
   _xSlrQ_Q := 0401; 
   {
      if (_Pzj_ASS7I)
         print (V3maAvi); 
      else 
         newline; 
   }
   _eH1edPRlf__8i(); 
   newline; 
   {
   }
}
_gbliO(_v8, _slo, _dG7b, _G1D$cTZP){local NrrNHlso, _z, _j96HzY, Bkwn, cJfLHNp, _GhuvIbD9; 
   return 35; 
   _f1EfnK5J := qi; 
   {
   }
}
_KX(Otr4f, h, azazL){local veCdc, Cig, Dn; 
   print 0742 - 0005; 
   newline; 
   newline; 
}
cT(_KgA, _HE, hQU$e){local _Q, _$j, _i_, _Hx; 
   {
      printch !_A - !!!5; 
      newline; 
      {
      }
   }
   return !330; 
   while (_K)
      {
      }
   {
   }
}
_nFu(t){local ZRLXUuAi, d; 
}
aiy(){
}