// test_800_35.B
begin
   _Gh(_RBSOn$k, _IaoYDR < d, _rCA, 7); 
   print !_K(!0450) <= (!_qDlhj0G(_LR && !(_4), 211956325, _S, _DERT5V, 960) - 8); 
   return 687 + 4; 
   _qs(16); 
   newline; 
   newline; 
end
_Og(z, _2, _FOn0, _rZVMCpGmYoWzz, _qTi, _Kh1){local _LRj, _X, _jxH, _p, _5oz, mTLo8V, EOK; 
   {
      if (7404675 || 6322)
         return !!_pQlSBgZ(); 
      else 
         println tOJbJ5() + _tJXN(126987); 
      if (580)
         newline; 
      else 
         while (H)
            newline; 
      if ((0 == 866) || !012)
         {
            newline; 
         }
      else 
         printch !yuBns8 < !MlC70(5 < 28); 
      newline; 
      print vgOD(); 
      {
      }
      newline; 
   }
   println 294 + 24; 
   printch (4) < !_Si; 
   if ((4) + 87038)
      printch T8 < 648; 
   else 
      if (!7 + 26)
         print 794934 / 5; 
      else 
         printch 833; 
   if (86)
      newline; 
   else 
      {
      }
   _Km_ := (!!8607 < 066) - _AD; 
   while (!_r)
      if ((439548) && 16389)
         {
            {
            }
            {
            }
         }
      else 
         if (xPoV)
            {
            }
         else 
            newline; 
   {
   }
   printch (uVmS_R); 
   {
      return SKFWV9n; 
      newline; 
   }
   newline; 
   {
   }
   {
   }
}
U(_w$9E, khIvAXB2cVG9$iOBbCI7, Be, _bj, L){local u, _9Z, _j9, mgBA3Iboo; 
   newline; 
   if (!09561 && 1)
      print (2939657) == c; 
   else 
      {
         newline; 
      }
}
L(_H6aXDnQJkEIyPs2f, _ocK, _P, _U, _JaRx, tEvdg3, _FUki){local _NuTMIS_nGsu, _X, _cTV, _KtT; 
   {
   }
   ky70jt5iDL(); 
   print !786 - _pPPT; 
   newline; 
}
_unQrC7(__t, _aKrM, FZ){local _lFl0yFsAJa, _lsSQGPNNTLVz9YJoezmd, F; 
   newline; 
   newline; 
   newline; 
}
_tU(){
}
_qf(_$rYw_ZwW, n){local _K4Z, _Nvc, _vf; 
   printch _y; 
   newline; 
}
_68U1(_06){local _U, _Pkmf; 
}
t(e){
}
e(_tO){
}
LkpxTF96KLTVT01rACU6v(){
}
oOP(){
}