// test_400_14.B
begin
   print 2 || !wR1dKucbntfc(); 
   while (!!!4808 + (487 - (rK0w == ll$TZ)))
      printch !(_c98) * !5359; 
   if (50 < !61978)
      println 3 + _Z(); 
   else 
      printch (_bzD + _6) == 3; 
   while (370617)
      println (_IxijXITk() <= _A8f9x) / e$KN$wPGK; 
   {
      print jQ(P) / 32; 
      print !4050 < LD5nr7f; 
      if (LWvaRZ)
         println _6; 
      else 
         {
         }
      {
      }
   }
   Y4S1B(); 
   K1LoQSNE0luHE(); 
   newline; 
   {
   }
   if (414)
      newline; 
   else 
      print 5; 
   {
   }
end
_75VhKJ(v, _jz){local _NHZC, LQeN2WoWQurcKHTIZjm, W; 
   newline; 
   {
      {
      }
   }
   printch 4; 
   return wZ; 
   println 6; 
   {
   }
}
omtILs2(NL$43, svqLFy, _N, ArGxp5qj){local _Kr, _03P, _vFsd, Uu, hO; 
   println GazF; 
   printch !057 * n; 
   newline; 
   println lu; 
   newline; 
   newline; 
   {
   }
}
_LZka_7(){
   newline; 
}
_l(){
}
_R(){local kSfO; 
}