// test_400_26.B
begin
   print (_Z6KI(_Buj * !!084) + _WbVn(LexH)) * (!28563194 * (06589674)); 
   newline; 
   print !6421 && (_S); 
   print A(458 || Zaobx) - 3; 
   {
   }
   newline; 
end
_MUa(_9, _vt2Y, ub2WE){local t, _Dd, _0; 
   newline; 
   newline; 
   newline; 
   while (zwh56FDS)
      RcCsqEec3wK := U7; 
   println 27; 
}
_jh(dOj7Ft, Gmt1, _b, EoW){local hI4Xqw, _M8U, hTuh_ThrcWceWiK, _ydDj1dMU, _3cr, Us, l3kw_DWt; 
   println ((!_Hw <= DRxY) - E); 
   newline; 
   {
   }
   newline; 
   {
   }
}
XtNrC(__, _p){local _8SyM, __op0TvEo7DrI9yoZyvpn2EUmOwJ9, _LtDWDNLBY; 
   while ((4653) == 2408)
      printch !!(01); 
   printch (9); 
   if (908167)
      {
      }
   else 
      print 8; 
   {
   }
}
GR(qb_, _FS, I, _p){local _tJTp0Il; 
   {
      printch ftDjQu; 
      {
      }
   }
   newline; 
   {
   }
}
_4(u, _ov, _EbxAMy){local _0, _X5, _Y; 
}
_d2(xQpstfd3g0TJI4RixjrcRCe){
}