// test_200_19.B
begin
   {
      return (5763); 
   }
   newline; 
   {
   }
   n(); 
end
dSQ(_oI5, _5uZlH, gGV4){local _PXRL, _t, K4, yUuhSU; 
   {
   }
   newline; 
   print 787; 
}
_y(_obnQ7){local _9f4RKHUMxGUd, _O; 
   {
      println 8; 
      newline; 
   }
   return 37 || 7363; 
   newline; 
}
_JXb7bER(_tvwxzV9pgglS, FYJpI, _w, _wq){local _B, _FySsz; 
   while (_bv)
      print j; 
}
U(Cs){local GxN; 
}
KDw(){local Ty; 
   {
   }
   newline; 
   {
   }
   newline; 
}