// test_400_10.B
begin
   return H - 9; 
   {
      newline; 
      {
      }
   }
   {
      newline; 
   }
   newline; 
   println 7; 
   return 394496; 
   if (_oM)
      {
      }
   else 
      newline; 
   while (U65O6wX)
      newline; 
   {
   }
end
GivM(){local L, VVaww$i, L, _Cokebh2MJ6; 
   return pa; 
   {
   }
   return !2 || 23; 
}
_yn4wa(_n, _1){local _1jitz, _Pd6, _oqYN; 
   println !!4861 / _j4auJxLi; 
   {
   }
}
UjMI(vkq, q0giy, _S6cR, Fj7, _A0N){local _tQH, VWFaRjU6, _LI; 
   {
   }
   return _V < (f); 
   println _q$pZCmXfO() / _vm3f(); 
}
hCWGMd(_oylM, _R, _pl, _pdJ, M, c){local _ca, rr, g, QF, _Cn_W; 
   K(); 
   dF1K := _re7QtzZ; 
   println q <= 2; 
}
gcP(FBpngF, _oCl, _S, d){local l, _$i, l; 
   println !(2) - _aEXas1pe(); 
   return 141 || 6145; 
   printch s; 
   while (pl)
      return _lTy3bXYq9rMPwk3x5; 
   newline; 
}
_ApeZrgC(_l0t40, dWL){
   printch 366172; 
}