// test_400_5.B
begin
   return 97 - z5l3CO47pj3SkP; 
   return _W4wQ3g_NABS; 
   if (_W)
      {
      }
   else 
      newline; 
end
Q(_ZHr, _Hm, GH, _PH, lW, _Gznb8Xr, pvxPk3XS, _kASV, aNNJ){local _2P, _gcw, _E$cm1, _QaU, _iOJjZmRKj, _FoCH, _9h5cI, EXeI, _Ym, _avE; 
   print ((h) == !(_M4HWI0qeL)) * !8; 
   print !2 || _vOT; 
   Q(); 
}
_uc(_YV){local _dBjoj7WLb; 
}
XH(_Ca, _SX, _$MgI7L, Gx, _FSWxU$AAVczU2izm4YMZe, Du){local _yj, _w, jUWMJf, _tVt; 
   println !OnHaR7z_; 
   print !253 / BiuJ; 
   newline; 
}
_$y(){local NfDo, Z0b8WXwot; 
   _Wt(012 < vf); 
   return !_Wi5; 
   {
   }
   printch _F; 
   newline; 
}
Qq7K(O, _qO4bc_36, _nkC, _r8){
   println _Tt; 
   return x$0XNQaJHUa7n1; 
}
EA(){
}
_cg(){
   {
      newline; 
      newline; 
   }
   newline; 
}
Ag26PoA(){
}
_m44(_Rf5Tx, _a){local g, _xE; 
   println 63; 
}
Tw1(){
}
_YPql(){local vZ3AxF; 
   newline; 
}