// test_400_23.B
begin
   return b(_p_v() / (011), oMK, !taL, TkhZ) && !_i(3); 
   printch 61223; 
   _G$TPQ0 := 55209; 
   while (oOZ)
      if (12)
         newline; 
      else 
         {
         }
   {
   }
end
_BzEpAV(W7, dJ, _CiAW){local j$1j411R; 
   _mxe := 897; 
   {
   }
   {
   }
}
jLl7(IfJN, AYz){local C, zc7Rs8x, _GOiE, _wmn; 
   printch (778) * 0; 
   if (648)
      return (7) + !2366; 
   else 
      _741DrEWs35$tjrv6B5V8JvcCnQJX9F2bI(); 
   _5qj_w(); 
   newline; 
   newline; 
   {
   }
}
_aeSH(_JJKcC, _JUZ, _I20Kklfj4Jvo7p, xWSN){local _CqIPa; 
   newline; 
   newline; 
   newline; 
}
_68zP5EIu18Czy(_gBs, e, _jV, _M){
   println _l09S7EtOcLM2; 
   printch _y$v; 
   {
   }
   println A - 818; 
   e3P(4742 || _r4qprL2l, 1); 
   if (_a || _fMpw0FUAoFU4sNEAcbam)
      newline; 
   else 
      {
      }
}
Mvn5(_Uq, sq7yL){local _3, m; 
   println 353 <= _iE; 
   print 6; 
   {
      {
      }
      while (2)
         print 857 && _8Df6kEp; 
   }
   newline; 
   newline; 
   if (v)
      {
      }
   else 
      newline; 
}
sE(){local _b7; 
   {
   }
}
dW(){
}